# Generated by Django 3.1.3 on 2021-01-14 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=75)),
                ('short_name', models.CharField(max_length=4, unique=True)),
                ('sport', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=75)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.team')),
            ],
            options={
                'unique_together': {('team', 'domain_name')},
            },
        ),
        migrations.CreateModel(
            name='BFName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bfname', models.CharField(max_length=40)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.domain')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'unique_together': {('domain', 'bfname')},
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.CharField(max_length=40)),
                ('host_password', models.CharField(max_length=128)),
                ('interests', models.CharField(max_length=16)),
                ('offer_code', models.CharField(max_length=30)),
                ('auto_renew', models.BooleanField()),
                ('bfname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.bfname')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
